### ISSUE TITLE
Imprint & Datenschutz

### ISSUE THREAD

**Issue by tschuhmacher** [mikro-kit/mikro-kit.github.io#21]
- [x] Kannst du uns da gute Vorlagen empfehlen?

Hier fehlt noch der tatsächliche Inhalt! Siehe letzter Kommentar!

**Comment by tschuhmacher** [comment]
Zum Thema Impressum und der DSVGO kann ich auch nur nach bestem Wissen und Gewissen beraten, hier findet man im Netz Hinweise z.B.:
- Impressum: https://www.datenschutzbeauftragter-info.de/fachbeitraege/impressum-wie-muss-es-aussehen/
oder auch https://www.e-recht24.de/impressum-generator.html
- zur DSVGO muss man überlegen, wo Daten von euch gespeichert und verarbeitet werden.
1) Zum Beispiel muss benannt werden, wenn ihr Mailadressen aus dem Kontaktformular für einen Newsletter speichert.
2) von technischer Seite muss benannt werden, wenn z.B. über 'Cookies' (Marker, die Browser gespeichert werden) Nutzer der Seite identifizierbar werden. Das passiert auf der Seite aktuell nicht.
3) Es sollte benannt werden, dass die Seite über GitHub Pages zu Verfügung gestellt wird sowie der Dienstleister für das Kontaktformular (z.B. FormKeep).

**Comment by tschuhmacher** [comment]
Sind als Dateien angelegt.

@LydiaDimitrow @magalitosato 
-> Das Impressum müsste mikro-kit generieren / überarbeiten
-> Die Datenschutzbeschreibung würde ich zu den Punkten Cookies / Github / Kontaktformular schreiben, die müsste mikro-kit dennoch absegnen und ggf. durch eigene Punkt ergänzen

**Comment by LydiaDimitrow** [comment]
Test

**Comment by LydiaDimitrow** [comment]
Lieber Timo, ich weiß nicht, ob ich das gerade richtig mache, aber ich versuchs mal ...

Was mir noch am dringendsten fehlt, sind eine Vorlage für das noch fehlende Projekt (Qui a peur d'Hamlet) und die richtige Anzahl an Vorlagen für die Presseartikel. Wir brauchen in beiden Sprachen jeweils zwei Presseartikel. Könntest du mir die anlegen, damit ich die mit Inhalt füllen kann?

Merci!
Lydia

**Comment by tschuhmacher** [comment]
Hallo Lydia! Es hat zumindest geklappt, das ich deine Nachricht bekommen habe! Du kannst auch gern Issues (grüner Button oben links) anlegen und sie mir zuweisen! Dann können wir direkter zu einzelnen Problemen kommunizieren.

Ich habe jetzt zwei Seiten für de/fr "Peur-Hamlet" angelegt, sowie je 10 Dateien (5 Projekte x 2 Artikel) in 2 Sprachen angelgt.

**Comment by LydiaDimitrow** [comment]
Lieber Timo, super! Danke fürs schnelle Reagieren! Ich habe auch fleißig weiter Inhalt eingefügt. Könntest du noch zwei Presse-Buttons für den Auftrag anlegen? Morgen schicke ich dir ein Foto für Qui a peur d'Hamlet? und kümmere mich noch ums Impressum und die DSVGO. Was denkst du, wie schnell können wir dann online gehen? Tausend Dank für alles, Lydia

**Comment by LydiaDimitrow** [comment]
Impressum: erledigt
Datenschutz: Kontaktformular-Passus fehlt

**Comment by tschuhmacher** [comment]
> Datenschutz: Kontaktformular-Passus fehlt

aufgenommen als #31
