### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by LydiaDimitrow** [mikro-kit/mikro-kit.github.io#30]
Im Foster steht in der französischen Ansicht noch

FR Impressum
FR Datenschutz

Beide Dokumente sind bisher nur auf Deutsch, weil wir sie anscheinend auch im Moment nur für Deutschland brauchen, also kann das FR einfach weg. Merci!

**Comment by tschuhmacher** [comment]
- Impressum: hier bin ich mir nicht sicher, wie das geregelt ist..
- Datenschutz: diese Bestimmungen gelten EU-weit, wobei ich mich frage, wie definiert wird in welcher Sprache die angeboten werden..?
