### ISSUE TITLE
Domain verknüpfen

### ISSUE THREAD

**Issue by tschuhmacher** [mikro-kit/mikro-kit.github.io#32]
- [x] Strato-Unterlagen aus Google Drive an Timo
- [x] SSL in Strato zuweisen
- [x] Funktion in Strato setzen
- [x] testen

Um Domains Github-Pages zu zuweisen:
- bei Strato Subdomain www. ~ erstellen
- Subdomain CNAME (unter DNS Einstellung) an <repo>.github.io. verweisen (WIchtig: Subdomain zuweisen! & Punkt am Ende von github.io!)
- Domainname in den Einstellung des Repo eintragen!
- fertig!

**Comment by LydiaDimitrow** [comment]
Lieber Timo, kannst du kurz ein kleines Update geben? Wann denkst du, kannst du die Domain verknüpfen? Brauchst du noch was von uns? Liebe Grüße, Lydia

**Comment by tschuhmacher** [comment]
Liebe Lydia, mir sind noch drei Dinge aufgefallen, die ich morgen beheben kann:
- Titel-Bilder werden bei über 1500px zu klein dargestellt
- das Seitenmenü ist am iPhone nicht scrollbar
- im Footer müssen für die mobile Version Impressum und Datenschutz eingerückt werden

Morgen Abend werde ich dann die Domain mit der Seite verknüpfen.

Liebe Grüße Timo!

**Comment by LydiaDimitrow** [comment]
Lieber Timo,

Du passt wunderbar zu mikro-kit: Du bist ein Perfektionist! :-)

Vielen Dank!
Lydia

**Comment by tschuhmacher** [comment]
bei mir funktioniert es jetzt, auch als sichere Verbindung. Bittet testet selber nochmal!
