### ISSUE TITLE
Finaler Review

### ISSUE THREAD

**Issue by tschuhmacher** [mikro-kit/mikro-kit.github.io#33]
- [x] Desktop: alle Seiten nochmal durchschauen
- [x] Mobile: alle Seiten nochmal durchschauen
- [ ] ~~Kontaktformular testen~~ siehe #34

**Comment by LydiaDimitrow** [comment]
Habe einen Test im Kontaktformular abgesendet. Text stimmt aber noch nicht?

**Comment by LydiaDimitrow** [comment]
Gibst du mir noch mal Bescheid, wenn ich alle Seiten durchschauen soll (also wenn deiner Meinung nach alle Änderungen eingepflegt sind)? Merci!

**Comment by tschuhmacher** [comment]
Ja, mache ich. Ich bin noch gar nicht fertig.. ich hatte nur eben noch to-dos gesammelt. Sorry

**Comment by LydiaDimitrow** [comment]
Achso, kein Problem! Hab mich nur gleich so angesprochen gefühlt! :) Dann bis später! Vielen Dank!

**Comment by tschuhmacher** [comment]
von meiner Seite bin ich erstmal durch, die Domain würde ich verknüpfen, wenn alle Seiten nochmal durchgeschaut sind! Die Problematik zum Kontaktformular habe ich in #34 zusammengefasst. Dazu können wir auch nochmal sprechen. Beste Grüße Timo

**Comment by LydiaDimitrow** [comment]
Ich sehe keinen Fehler mehr!

Die Problematik zum Kontaktformular (#34) vertagen wir auf Phase 2.

Good to go! Aufregend!!!

**Comment by LydiaDimitrow** [comment]
Detail: In der mobilen Ansicht ragt der Stücktitel "Qui a peur d'Hamlet?" aus seinem Kreis. Solche Schönheitsfehler finde ich aber gerade echt nicht so wichtig.
