### ISSUE TITLE
Kontaktformular Funktionalität

### ISSUE THREAD

**Issue by tschuhmacher** [mikro-kit/mikro-kit.github.io#9]
Über Formingo..? Siehe jekyllrb.com

**Comment by tschuhmacher** [comment]
- [Getform](https://getform.io) sammelt recht viele Daten ist aber laut eigener Angabe DSGVO-konform https://getform.io/legal/privacy-policy
- [99inbound](https://www.99inbound.com/) ist laut eigenen Angaben DSGVO-konform https://www.99inbound.com/legal/policies.html

**Comment by tschuhmacher** [comment]
Funktionert jetzt über 99inbound
-> Rechtliches muss noch geklärt werden #34

**Comment by rathboma** [comment]
Hey! I run 99Inbound. I'm British, so I have some sensitivity to EU privacy policies.  If you have any legal questions, please just let me know. matthew at 99inbound dot com.

Found this issue link from a google search!
